### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pyproject.toml'

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/image-titler#102]
When I install image-titler on my laptop, it fails to find the pyproject.toml file for whatever reason. I assume there's some usual pathing issue. 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python312\Scripts\image-titler-gui.exe\__main__.py", line 4, in <module>
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python312\Lib\site-packages\scripts\gui.py", line 24, in <module>
    from imagetitler import __version__
  File "C:\Users\jerem\AppData\Local\Programs\Python\Python312\Lib\site-packages\imagetitler\__init__.py", line 3, in <module>
    with open("pyproject.toml", "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'pyproject.toml'
```

I don't know if this is a Python 3.12 issue, or if this is an issue everywhere.

**Comment by jrg94** [comment]
By the way, running from source is a non-issue.
