### ISSUE TITLE
Some Logos Fail to Render

### ISSUE THREAD

**Issue by jrg94** [TheRenegadeCoder/image-titler#53]
I attempted to add an old log of my to the image, and I ran into an error:

![Logo Overlay Error](https://user-images.githubusercontent.com/11050412/80751777-6046da00-8af8-11ea-9876-3e0f0eefb059.png)

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jeremy Grifski\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "E:/Projects/trc-image-titler/image_titler/gui.py", line 83, in update_view
    self._render_preview(title=title, tier=tier, logo_path=logo_path)
  File "E:/Projects/trc-image-titler/image_titler/gui.py", line 96, in _render_preview
    self.menu.current_edit = process_image(self.menu.image_path, title, tier=tier, logo_path=logo_path)
  File "E:\Projects\trc-image-titler\image_titler\utilities.py", line 258, in process_image
    _draw_logo(cropped_img, logo)
  File "E:\Projects\trc-image-titler\image_titler\utilities.py", line 127, in _draw_logo
    img.paste(logo, (LOGO_PADDING, height - LOGO_SIZE[1] - LOGO_PADDING), logo)
  File "E:\Projects\trc-image-titler\venv\lib\site-packages\PIL\Image.py", line 1494, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask
```

I haven't had time to investigate this, so I figured I'd drop the issue here for now. I'm wondering if it's because this logo is a jpg. Maybe we should restrict logos to pngs.

**Comment by jrg94** [comment]
Nevermind, I got this same issue for a different logo:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jeremy Grifski\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "E:/Projects/trc-image-titler/image_titler/gui.py", line 83, in update_view
    self._render_preview(title=title, tier=tier, logo_path=logo_path)
  File "E:/Projects/trc-image-titler/image_titler/gui.py", line 96, in _render_preview
    self.menu.current_edit = process_image(self.menu.image_path, title, tier=tier, logo_path=logo_path)
  File "E:\Projects\trc-image-titler\image_titler\utilities.py", line 258, in process_image
    _draw_logo(cropped_img, logo)
  File "E:\Projects\trc-image-titler\image_titler\utilities.py", line 127, in _draw_logo
    img.paste(logo, (LOGO_PADDING, height - LOGO_SIZE[1] - LOGO_PADDING), logo)
  File "E:\Projects\trc-image-titler\venv\lib\site-packages\PIL\Image.py", line 1494, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask
```

**Comment by jrg94** [comment]
Here are the culprits:

![icon-360x360](https://user-images.githubusercontent.com/11050412/80752135-0397ef00-8af9-11ea-90ff-44dfa0b1685e.png)

![icon-cut-down-square](https://user-images.githubusercontent.com/11050412/80752142-0561b280-8af9-11ea-888f-67443d9cd762.jpg)
